version: "3.9"
   
services:
  web:
    image: claudeperrin228/claudeperrin-djangotest:latest
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:  
      - ./boookz:/boookz
      - ./authentication:/authentication
      - ./boookzdata:/boookzdata
      - ./frontend:/frontend
      - ./media:/media
    ports:
      - "80:80"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"
volumes:
  postgres_data:
  book_exchanger:
    external: true

